# Generated by Django 4.1 on 2022-10-17 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privateUrlDocument', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('publicUrlDocument', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VdxPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperNumber', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('issuer', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('operator', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('nid', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('nvh', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('lines', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('currentState', models.IntegerField(choices=[(1, 'CREATD'), (2, 'ISSUED'), (3, 'CHECKED'), (4, 'TREATED'), (5, 'PAID'), (6, 'RECEIVED'), (7, 'DELIVERED')])),
                ('createDateTime', models.DateTimeField(blank=True, null=True)),
                ('issueDateTime', models.DateTimeField(blank=True, null=True)),
                ('deliveredDateTime', models.DateTimeField(blank=True, null=True)),
                ('docImma', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashTx', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('txn', models.IntegerField(choices=[(1, 'Create'), (2, 'Issue'), (3, 'Check'), (4, 'Treat'), (5, 'Pay'), (6, 'Receive'), (7, 'Deliver')], default=1)),
                ('paperNumber', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('issuer', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('currentOperator', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('newOperator', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('nid', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('nvh', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('lines', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('docHash', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('vat', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('payRef', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_transaction', to='ULinkPublic.vdxpaper')),
            ],
        ),
    ]
