# Generated by Django 4.1 on 2022-10-17 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ULinkPublic', '0003_transaction_nas_vdxpaper_nas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdxpaper',
            name='auteur',
        ),
        migrations.AlterField(
            model_name='vdxpaper',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuer_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vdxpaper',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
