# Generated by Django 4.1 on 2022-10-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULinkPublic', '0004_remove_vdxpaper_auteur_alter_vdxpaper_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdxpaper',
            name='currentState',
            field=models.IntegerField(choices=[(1, 'CREATD'), (2, 'ISSUED'), (3, 'CHECKED'), (4, 'TREATED'), (5, 'PAID'), (6, 'RECEIVED'), (7, 'DELIVERED')], default=1),
        ),
    ]
