# Generated by Django 4.1 on 2022-10-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ULinkPublic', '0005_alter_vdxpaper_currentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_transaction', to='ULinkPublic.vdxpaper'),
        ),
        migrations.AlterField(
            model_name='vdxpaper',
            name='currentState',
            field=models.IntegerField(choices=[(1, 'CREATD'), (2, 'ISSUED'), (3, 'CHECKED'), (4, 'TREATED'), (5, 'PAID'), (6, 'RECEIVED'), (7, 'DELIVERED')]),
        ),
    ]
