# Generated by Django 4.1 on 2022-11-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULinkPublic', '0006_alter_transaction_paper_alter_vdxpaper_currentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdxpaper',
            name='currentState',
            field=models.IntegerField(choices=[(1, 'CREATED'), (2, 'ISSUED'), (3, 'CHECKED'), (4, 'TREATED'), (5, 'PAID'), (6, 'RECEIVED'), (7, 'DELIVERED')]),
        ),
    ]
