# Generated by Django 4.1 on 2022-11-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ULinkPublic', '0007_alter_vdxpaper_currentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='docHash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dochash_ipfs', to='ULinkPublic.ipfs'),
        ),
    ]
