# Generated by Django 4.1 on 2022-11-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RqPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperNumber', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('issuer', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('vdxPaperRef', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='requester fullname')),
                ('nas', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='request nas')),
                ('nid', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='requester nid')),
                ('nvh', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('lines', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WkfHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflowState', models.IntegerField(choices=[(1, 'RECEIVE'), (2, 'SEND'), (3, 'COMPLETE')])),
                ('description', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rqpaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rq_paper', to='ULinkAdmin.rqpaper')),
            ],
        ),
    ]
