# Generated by Django 4.1 on 2022-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULinkAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rqpaper',
            name='paperNumber',
            field=models.CharField(blank=True, default='', max_length=600, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rqpaper',
            name='vdxPaperRef',
            field=models.CharField(blank=True, default='', max_length=600, null=True, unique=True),
        ),
    ]
