# Generated by Django 4.1 on 2022-11-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULinkAdmin', '0002_alter_rqpaper_papernumber_alter_rqpaper_vdxpaperref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rqpaper',
            old_name='issuer',
            new_name='operator',
        ),
    ]
