# Generated by Django 4.1 on 2022-11-18 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ULinkAdmin', '0003_rename_issuer_rqpaper_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rqpaper',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_from_sc', to=settings.AUTH_USER_MODEL),
        ),
    ]
