# Generated by Django 4.1 on 2022-10-04 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wkf_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wkf_Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('est_initiale', models.BooleanField(default=False)),
                ('est_finale', models.BooleanField(default=False)),
                ('est_decisive', models.BooleanField(default=False)),
                ('num_ordre', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wkf_Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=30, unique=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Wkf_Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('traitement', models.CharField(blank=True, max_length=250, null=True)),
                ('num_ordre', models.IntegerField(blank=True, null=True)),
                ('identifiant_cle', models.IntegerField(blank=True, null=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions_transitions', to='ULinkBackOffice.wkf_condition')),
                ('etape_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_etapes_destination', to='ULinkBackOffice.wkf_etape')),
                ('etape_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_etapes_source', to='ULinkBackOffice.wkf_etape')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_of_transition', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Wkf_Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workflow_etapes', to='ULinkBackOffice.wkf_etape')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workflow_utilisateurs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wkf_etape',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_workflows', to='ULinkBackOffice.wkf_workflow'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('type_document', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('url_document', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('index', models.TextField(blank=True)),
                ('source_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('metadonnees', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=600, null=True)),
                ('taille', models.CharField(blank=True, max_length=100, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_document_oej', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
